# Generated by Django 5.1.7 on 2025-04-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nomb_org', models.CharField(verbose_name=100)),
                ('cont_org', models.IntegerField(verbose_name=11)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
