# Generated by Django 5.1.7 on 2025-04-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cont_org',
            field=models.BigIntegerField(verbose_name=11),
        ),
    ]
